src/Entity/Panier.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PanierRepository")
 */
class Panier
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Coupon", inversedBy="paniers")
     */
    private $coupons;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="paniers")
     */
    private $user;

    /**
     * @ORM\Column(type="float")
     */
    private $total_price;

    /**
     * @ORM\Column(type="date")
     */
    private $emmission;

    /**
     * @ORM\Column(type="float")
     */
    private $price_shipping;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $token;

    /**
     * @ORM\Column(type="integer")
     */
    private $status;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $paiement_date;

    /**
     * @ORM\Column(type="float")
     */
    private $total_reduction;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Abonnement", mappedBy="panier",cascade={"persist"})
     */
    private $abonnements;

    /**
     ** @ORM\OneToMany(targetEntity="App\Entity\Commande", mappedBy="panier",cascade={"persist"})
     */    
    private $commandes;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $stripe_charge_id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $remboursement;

    public function __construct()
    {
        $this->price_shipping = 0;
        $this->total_reduction = 0;
        $this->total_price = 0;
        $this->status = 0;
        $this->token = 0;
        $this->emmission = new \DateTime();
        $this->coupons = new ArrayCollection();
        $this->commandes = new ArrayCollection();
        $this->abonnements = new ArrayCollection();
    }

    public function refresh_price(){
        $sommes = 0;
        foreach ($this->commandes as $key => $commande) {
            $sommes +=  $commande->getTotalPrice();
        }
        foreach ($this->abonnements as $key => $abonnement) {
            $sommes +=  $abonnement->getFormule()->getPrice();
        }
        $reduction = 0;
        foreach ($this->coupons as $key => $coupon) {
            if($coupon->getTypeReduction()){
                $reduction +=  $sommes*$coupon->getPriceReduction()/100;
            }else{
                $reduction +=  $coupon->getPriceReduction();
            }
        }
        $this->total_price =  $sommes;
        $this->total_reduction = $reduction;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|Coupon[]
     */
    public function getCoupons(): Collection
    {
        return $this->coupons;
    }

    public function addCoupon(Coupon $coupon): self
    {
        if (!$this->coupons->contains($coupon)) {
            $this->coupons[] = $coupon;
        }
        $this->refresh_price();

        return $this;
    }

    public function removeCoupon(Coupon $coupon): self
    {
        if ($this->coupons->contains($coupon)) {
            $this->coupons->removeElement($coupon);
        }
        $this->refresh_price();

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getTotalPrice(): ?float
    {
        return $this->total_price;
    }

    public function setTotalPrice(float $total_price): self
    {
        $this->total_price = $total_price;

        return $this;
    }

    public function getEmmission(): ?\DateTimeInterface
    {
        return $this->emmission;
    }

    public function setEmmission(\DateTimeInterface $emmission): self
    {
        $this->emmission = $emmission;

        return $this;
    }

    public function getPriceShipping(): ?float
    {
        return $this->price_shipping;
    }

    public function setPriceShipping(float $price_shipping): self
    {
        $this->price_shipping = $price_shipping;
        
        $this->refresh_price();

        return $this;
    }

    /**
     * @return Collection|Commande[]
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setPanier($this);
        }
        $this->refresh_price();

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->contains($commande)) {
            $this->commandes->removeElement($commande);
            // set the owning side to null (unless already changed)
            if ($commande->getPanier() === $this) {
                $commande->setPanier(null);
            }
        }
        $this->refresh_price();

        return $this;
    }


    /**
     * @return Collection|Abonnement[]
     */
    public function getAbonnements(): Collection
    {
        return $this->abonnements;
    }

    public function addAbonnement(Abonnement $abonnements): self
    {
        if (!$this->abonnements->contains($abonnements)) {
            $this->abonnements[] = $abonnements;
            $abonnements->setPanier($this);
        }
        $this->refresh_price();

        return $this;
    }

    public function removeAbonnement(Abonnement $abonnements): self
    {
        if ($this->abonnements->contains($abonnements)) {
            $this->abonnements->removeElement($abonnements);
            // set the owning side to null (unless already changed)
            if ($abonnements->getPanier() === $this) {
                $abonnements->setPanier(null);
            }
        }
        $this->refresh_price();

        return $this;
    }



    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(string $token): self
    {
        $this->token = $token;

        return $this;
    }
    public function initToken(): self
    {
        $this->token = md5($this->getId());

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getPaiementDate(): ?\DateTimeInterface
    {
        return $this->paiement_date;
    }

    public function setPaiementDate(\DateTimeInterface $paiement_date): self
    {
        $this->paiement_date = $paiement_date;

        return $this;
    }

    public function getTotalReduction(): ?float
    {
        return $this->total_reduction;
    }

    public function setTotalReduction(float $total_reduction): self
    {
        $this->total_reduction = $total_reduction;

        return $this;
    }

    public function __toString (  ) : string{
        return $this->getToken();
    }

    public function getStripeChargeId(): ?string
    {
        return $this->stripe_charge_id;
    }

    public function setStripeChargeId(?string $stripe_charge_id): self
    {
        $this->stripe_charge_id = $stripe_charge_id;

        return $this;
    }

    public function getRemboursement(): ?int
    {
        return $this->remboursement;
    }

    public function setRemboursement(?int $remboursement): self
    {
        $this->remboursement = $remboursement;

        return $this;
    }


}

src/Form/PanierType.php
<?php

namespace App\Form;

use App\Entity\Panier;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PanierType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('total_price')
            ->add('emmission')
            ->add('price_shipping')
            ->add('token')
            ->add('formules')
            ->add('coupons')
            ->add('user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Panier::class,
        ]);
    }
}

src/Controller/PanierController.php
<?php

namespace App\Controller;

use App\Entity\Panier;
use App\Form\PanierType;
use App\Service\ProductService;
use App\Repository\PanierRepository;
use Symfony\Component\Routing\Generator\UrlGenerator;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use App\Service\StripeService;

use Stripe\Stripe;
use \Stripe\Charge;

/**
 * @Route("/dashboard/panier")
 */
class PanierController extends AbstractController
{   
    private $stripe_s;
    private $panierRepository;

    public function __construct(StripeService $stripe_s, PanierRepository $panierRepository){
        $this->stripe_s = $stripe_s;
        $this->panierRepository = $panierRepository;
    }

    /**
     * @Route("/", name="panier_index", methods={"GET"})
     */
    public function index(PanierRepository $panierRepository): Response
    {
        return $this->render('panier/index.html.twig', [
            'paniers' => $panierRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="panier_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $panier = new Panier();
        $form = $this->createForm(PanierType::class, $panier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($panier);
            $entityManager->flush();

            return $this->redirectToRoute('panier_index');
        }

        return $this->render('panier/new.html.twig', [
            'panier' => $panier,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="panier_show", methods={"GET"})
     */
    public function show(Panier $panier): Response
    {
        return $this->render('panier/show.html.twig', [
            'panier' => $panier,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="panier_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Panier $panier): Response
    {
        $form = $this->createForm(PanierType::class, $panier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('panier_index');
        }

        return $this->render('panier/edit.html.twig', [
            'panier' => $panier,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="panier_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Panier $panier): Response
    {
        if ($this->isCsrfTokenValid('delete'.$panier->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($panier);
            $entityManager->flush();
        }

        return $this->redirectToRoute('panier_index');
    }

        /**
     * @Route("/confirm-remboursement/{id}", name="confirm_remboursement", methods={"GET"})
     */
    public function remboursement(Request $request, $id, \Swift_Mailer $mailer){
        $entityManager = $this->getDoctrine()->getManager();
        $panier = $this->panierRepository->find($id);
        $result = $this->stripe_s->refund($panier->getStripeChargeId());
        $panier->setRemboursement(2);
        $entityManager->flush();

        $url = $this->generateUrl('home', [], UrlGenerator::ABSOLUTE_URL);
        $content = "<p>Bonjour ".$panier->getUser()->getName().",<br> nous vous confirmons que votre demande de remboursement vient d'etre traitée</p>";
        try {
            $mail = (new \Swift_Message("Confirmation remboursement"))
                ->setFrom(["bahuguillaume@gmail.com" => 'EpodsOne'])
                ->setTo([$panier->getUser()->getEmail()=>$panier->getUser()->getEmail()])
                ->setBody(
                    $this->renderView(
                        'emails/mail_template.html.twig',['content'=>$content, 'url'=>$url]
                    ),
                    'text/html'
                );
            $mailer->send($mail);
        } catch (Exception $e) {
            print_r($e->getMessage());
        }

        $this->addFlash('success', "Remboursement confirmé");
        return $this->redirectToRoute('panier_index');                
    }
}

templates/panier/_delete_form.html.twig
<form method="post" action="{{ path('panier_delete', {'id': panier.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ panier.id) }}">
    <button class="btn">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2">
            <polyline points="3 6 5 6 21 6"></polyline>
            <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>
            <line x1="10" y1="11" x2="10" y2="17"></line>
            <line x1="14" y1="11" x2="14" y2="17"></line>
        </svg>
    </button>
</form>

templates/panier/edit.html.twig
{% extends 'admin/layout.html.twig' %}
{% block title %} {{parent()}} | Editer Panier {% endblock %}

{% block dataStructured %}{% endblock %}

{% block stylesheets %}
    {{parent()}}
    <link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/datatables.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/custom_dt_html5.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/dt-global_style.css')}}">
    <style type="text/css">
        .widget-content-area{box-shadow: none;}
    </style>
{% endblock %}
{% block body_bo %}
<div class="layout-px-spacing">
    <div class="row layout-top-spacing">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12" style="margin-bottom:24px;">
            <div class="statbox widget box box-shadow">
                <div class="widget-header">                                
                    <div class="row">
                        <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                            <h4>Nouveau Panier</h4>
    {{ include('panier/_form.html.twig', {'button_label': 'Update'}) }}
                        </div>
                    </div>
                </div>
                <div class="widget-content widget-content-area" style="height: 571px;">

    {{ include('panier/_delete_form.html.twig') }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascripts %}
    {{parent()}}

{% endblock %}

templates/panier/index.html.twig
{% extends 'admin/layout.html.twig' %}
{% block title %} {{parent()}} | Panier {% endblock %}{% block stylesheets %}
{{parent()}}
<link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/datatables.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/custom_dt_html5.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/dt-global_style.css')}}">

<!-- BEGIN THEME GLOBAL STYLES -->
<link href="{{asset('assetsBo/plugins/flatpickr/flatpickr.css')}}" rel="stylesheet" type="text/css">
<!-- END THEME GLOBAL STYLES -->

<!--  BEGIN CUSTOM STYLE FILE  -->
<link href="{{asset('assetsBo/plugins/flatpickr/custom-flatpickr.css')}}" rel="stylesheet" type="text/css">
    <!--  END CUSTOM STYLE FILE  -->

<style type="text/css">
   .widget-content-area{box-shadow: none;}
</style>
{% endblock %}
{% block body_bo %}
<div class="layout-px-spacing">
   <div class="row layout-top-spacing">
      <div class="col-12 layout-spacing">
         <div class="widget widget-chart-three">
            <div class="widget-heading">
               <div class="">
                  <h5 class="">List de Panier</h5>
               </div>
               <div class="dropdown  custom-dropdown">
                  <a class="dropdown-toggle" href="#" role="button" id="uniqueVisitors" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                     <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-more-horizontal">
                        <circle cx="12" cy="12" r="1"></circle>
                        <circle cx="19" cy="12" r="1"></circle>
                        <circle cx="5" cy="12" r="1"></circle>
                     </svg>
                  </a>
                  <div class="dropdown  custom-dropdown">
                     <a class="btn" href="{{ path('panier_new') }}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus">
                           <line x1="12" y1="5" x2="12" y2="19"></line>
                           <line x1="5" y1="12" x2="19" y2="12"></line>
                        </svg>
                        Ajouter
                     </a>
                  </div>
               </div>
            </div>
            <div class="widget-content widget-content-area br-6">

              <div class="wrapper-export">
                  <div>Exporter les commandes</div>
                  <form class="form-inline" action="{{path('export_facture')}}" method="POST">
                      Du &nbsp<input type="date" name="date_debut" class="form-control dateTimeFlatpickr" required>&nbsp Au &nbsp
                      <input type="date" name="date_fin" class="form-control dateTimeFlatpickr" required>&nbsp
                      <button type="submit"  class="btn btn-primary"> Exporter</button>
                  </form>
              </div>

               <div class="table-responsive mb-4 mt-4">
                  <table id="html5-extension" class="table table-hover non-hover" style="width:100%">
                     <thead>
                        <tr>
                           <th>User</th>
                           <th>Emission</th>
                           <th>Prix de Livraison</th>
                           <th>Token</th>
                           <th>Cout Total</th>
                           <th>Remboursement</th>
                           <th>actions</th>
                        </tr>
                     </thead>
                     <tbody>
                        {% for panier in paniers %}
                        <tr>
                          <td>{{ panier.user.email }}</td>
                           <td>{{ panier.emmission ? panier.emmission|date('Y-m-d') : '' }}</td>
                           <td>{{ panier.priceShipping }}</td>
                           <td><div class="badge badge-warning">{{ panier.token }}</div></td>
                           <td>{{ panier.totalPrice }}</td>
                           <td>
                              {% if panier.remboursement == 1 %}
                                <a href="{{path('confirm_remboursement', {'id':panier.id})}}" style="color:#007bff">confirmer</a>
                              {% endif %}
                              {% if panier.remboursement == 2 %}
                                <span>Rembousé</span>
                              {% endif %}
                           </td>
                           <td>
                              <a href="{{ path('panier_edit', {'id': panier.id}) }}">Editer</a>
                              {{ include('panier/_delete_form.html.twig') }}
                           </td>
                        </tr>
                        {% else %}
                        <tr>
                           <td colspan="6">Aucun element trouve</td>
                        </tr>
                        {% endfor %}
                     </tbody>
                  </table>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
{% endblock %}
{% block javascripts %}
{{parent()}}
<script src="{{asset('assetsBo/plugins/table/datatable/datatables.js')}}"></script>
<!-- NOTE TO Use Copy CSV Excel PDF Print Options You Must Include These Files  -->
<script src="{{asset('assetsBo/plugins/table/datatable/button-ext/dataTables.buttons.min.js')}}"></script>
<script src="{{asset('assetsBo/plugins/table/datatable/button-ext/jszip.min.js')}}"></script>    
<script src="{{asset('assetsBo/plugins/table/datatable/button-ext/buttons.html5.min.js')}}"></script>
<script src="{{asset('assetsBo/plugins/table/datatable/button-ext/buttons.print.min.js')}}"></script>

  <!-- BEGIN PAGE LEVEL SCRIPTS -->
  <script src="{{asset('assetsBo/plugins/flatpickr/flatpickr.js')}}"></script>
  <script src="{{asset('assetsBo/plugins/flatpickr/custom-flatpickr.js')}}"></script>
  <!-- END PAGE LEVEL SCRIPTS -->
  <script type="text/javascript">
    $('#sidebar .menu.menu-panier').addClass('active');
      var elements = document.getElementsByClassName("dateTimeFlatpickr");
      for (var i = 0; i < elements.length; i++) {
          var f2 = flatpickr(elements[i], {
              enableTime: true,
              dateFormat: "Y-m-d H:i",
          });
      }
  </script>

<script>
   $('#html5-extension').DataTable( {
       dom: '<"row"<"col-md-12"<"row"<"col-md-6"B><"col-md-6"f> > ><"col-md-12"rt> <"col-md-12"<"row"<"col-md-5"i><"col-md-7"p>>> >',
       buttons: {
           buttons: [
               { extend: 'copy', className: 'btn' },
               { extend: 'csv', className: 'btn' },
               { extend: 'excel', className: 'btn' },
               { extend: 'print', className: 'btn' }
           ]
       },
       "oLanguage": {
           "oPaginate": { "sPrevious": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-left"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>', "sNext": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>' },
           "sInfo": "voir page _PAGE_ of _PAGES_",
           "sSearch": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>',
           "sSearchPlaceholder": "Rechercher...",
          "sLengthMenu": "Results :  _MENU_",
       },
       "stripeClasses": [],
       "lengthMenu": [7, 10, 20, 50],
       "pageLength": 7 
   } );
      $('#sidebar .menu.menu-panier').addClass('active');

</script>
{% endblock %}

templates/panier/new.html.twig
{% extends 'admin/layout.html.twig' %}
{% block title %} {{parent()}} | Nouveau Panier {% endblock %}

{% block dataStructured %}{% endblock %}

{% block stylesheets %}
    {{parent()}}
    <link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/datatables.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/custom_dt_html5.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/dt-global_style.css')}}">
    <style type="text/css">
        .widget-content-area{box-shadow: none;}
    </style>
{% endblock %}
{% block title_page %}Panier{% endblock %}
{% block body_bo %}
    <div class="layout-px-spacing">
        <div class="row layout-top-spacing">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12" style="margin-bottom:24px;">
                <div class="statbox widget box box-shadow">
                    <div class="widget-header">                                
                        <div class="row">
                            <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                                <h4>Nouveau Panier</h4>
                            </div>
                        </div>
                    </div>
                    <div class="widget-content widget-content-area" style="height: 571px;">
                        {{ include('panier/_form.html.twig') }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{parent()}}

{% endblock %}

templates/panier/show.html.twig
{% extends 'admin/layout.html.twig' %}
{% block title %} {{parent()}} | Panier {% endblock %}

{% block dataStructured %}{% endblock %}
{% block body %}
    <h1>Panier</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ panier.id }}</td>
            </tr>
            <tr>
                <th>Total_price</th>
                <td>{{ panier.totalPrice }}</td>
            </tr>
            <tr>
                <th>Emmission</th>
                <td>{{ panier.emmission ? panier.emmission|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Price_shipping</th>
                <td>{{ panier.priceShipping }}</td>
            </tr>
            <tr>
                <th>Token</th>
                <td>{{ panier.token }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('panier_index') }}">back to list</a>

    <a href="{{ path('panier_edit', {'id': panier.id}) }}">edit</a>

    {{ include('panier/_delete_form.html.twig') }}
{% endblock %}