src/Entity/Coupon.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CouponRepository")
 */
class Coupon
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="integer")
     */
    private $type_reduction;

    /**
     * @ORM\Column(type="float")
     */
    private $price_reduction;

    /**
     * @ORM\Column(type="date")
     */
    private $start;

    /**
     * @ORM\Column(type="date")
     */
    private $end;

    /**
     * @ORM\Column(type="integer")
     */
    private $max_usage;

    /**
     * @ORM\Column(type="integer")
     */
    private $current_usage;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Panier", mappedBy="coupons")
     */
    private $paniers;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code;

    public function __construct()
    {
        $this->paniers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getTypeReduction(): ?int
    {
        return $this->type_reduction;
    }

    public function setTypeReduction(int $type_reduction): self
    {
        $this->type_reduction = $type_reduction;

        return $this;
    }

    public function getPriceReduction(): ?float
    {
        return $this->price_reduction;
    }

    public function setPriceReduction(float $price_reduction): self
    {
        $this->price_reduction = $price_reduction;

        return $this;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(\DateTimeInterface $start): self
    {
        $this->start = $start;

        return $this;
    }

    public function getEnd(): ?\DateTimeInterface
    {
        return $this->end;
    }

    public function setEnd(\DateTimeInterface $end): self
    {
        $this->end = $end;

        return $this;
    }

    public function getMaxUsage(): ?int
    {
        return $this->max_usage;
    }

    public function setMaxUsage(int $max_usage): self
    {
        $this->max_usage = $max_usage;

        return $this;
    }

    public function getCurrentUsage(): ?int
    {
        return $this->current_usage;
    }

    public function setCurrentUsage(int $current_usage): self
    {
        $this->current_usage = $current_usage;

        return $this;
    }

    /**
     * @return Collection|Panier[]
     */
    public function getPaniers(): Collection
    {
        return $this->paniers;
    }

    public function addPanier(Panier $panier): self
    {
        if (!$this->paniers->contains($panier)) {
            $this->paniers[] = $panier;
            $panier->addCoupon($this);
        }

        return $this;
    }

    public function removePanier(Panier $panier): self
    {
        if ($this->paniers->contains($panier)) {
            $this->paniers->removeElement($panier);
            $panier->removeCoupon($this);
        }

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }
}

src/Form/CouponType.php
<?php

namespace App\Form;

use App\Entity\Coupon;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class CouponType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('type_reduction', ChoiceType::class, [
                'choices' => [
                    'Type de reduction' => [
                        'Valeur' => 0,
                        'Pourcentage' => 1,
                    ]
                ],
            ])
            ->add('price_reduction')
            ->add('start', DateType::class, [
                'input'=>'datetime',
                'widget' => 'single_text',
                'html5' => false,
                'attr' => ['class' => 'dateTimeFlatpickr form-control'],
            ])
            ->add('end', DateType::class, [
                'input'=>'datetime',
                'widget' => 'single_text',
                'html5' => false,
                'attr' => ['class' => 'dateTimeFlatpickr form-control'],
            ])
            ->add('max_usage')
            ->add('current_usage')
            ->add('code')
            // ->add('paniers')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Coupon::class,
        ]);
    }
}

src/Controller/CouponController.php
<?php

namespace App\Controller;

use App\Entity\Coupon;
use App\Form\CouponType;
use App\Repository\CouponRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/dashboard/coupon")
 */
class CouponController extends AbstractController
{
    /**
     * @Route("/", name="coupon_index", methods={"GET"})
     */
    public function index(CouponRepository $couponRepository): Response
    {
        return $this->render('coupon/index.html.twig', [
            'coupons' => $couponRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="coupon_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $coupon = new Coupon();
        $form = $this->createForm(CouponType::class, $coupon);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($coupon);
            $entityManager->flush();

            return $this->redirectToRoute('coupon_index');
        }

        return $this->render('coupon/new.html.twig', [
            'coupon' => $coupon,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="coupon_show", methods={"GET"})
     */
    public function show(Coupon $coupon): Response
    {
        return $this->render('coupon/show.html.twig', [
            'coupon' => $coupon,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="coupon_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Coupon $coupon): Response
    {
        $form = $this->createForm(CouponType::class, $coupon);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('coupon_index');
        }

        return $this->render('coupon/edit.html.twig', [
            'coupon' => $coupon,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="coupon_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Coupon $coupon): Response
    {
        if ($this->isCsrfTokenValid('delete'.$coupon->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($coupon);
            $entityManager->flush();
        }

        return $this->redirectToRoute('coupon_index');
    }
}

templates/coupon/_delete_form.html.twig
<form method="post" action="{{ path('coupon_delete', {'id': coupon.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ coupon.id) }}">
    <button class="btn">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2">
            <polyline points="3 6 5 6 21 6"></polyline>
            <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>
            <line x1="10" y1="11" x2="10" y2="17"></line>
            <line x1="14" y1="11" x2="14" y2="17"></line>
        </svg>
    </button>
</form>

templates/coupon/_form.html.twig
<style type="text/css">
    button[type=submit]{float: right;}
</style>

{{ form_start(form) }}
    <div class="my-custom-class-for-errors">
        {{ form_errors(form) }}
    </div>

    <form>
        <div class="form-row mb-4">
            <div class="form-group col-md-6">
                <label for="inputEmail4">Nom du coupon</label>
                 {{ form_widget(form.nom, {'attr': {'class': 'form-control', 'placeholder':'Nom'}}) }} 
            </div>
            <div class="form-group col-md-3">
                <label for="inputCity">Type reduction</label>
                {{ form_widget(form.type_reduction, {'attr': {'class': 'form-control','type': 'decimal','required': false, 'placeholder':'Type reduction'}}) }} 
            </div>  
            <div class="form-group col-md-3">
                <label for="inputCity">Cout de la Reduction</label>
                {{ form_widget(form.price_reduction, {'attr': {'class': 'form-control','type': 'decimal','required': false, 'placeholder':'Cout de la Reduction'}}) }} 
            </div>  
        </div>
       
        <div class="form-row mb-4">
            <div class="form-group col-md-6">
                <label for="inputCity">Debut de validite</label>
                {{ form_widget(form.start, {'attr': {'placeholder':'Debut de validite'}}) }} 
            </div>
            <div class="form-group col-md-6">
                <label for="inputState">Expiration du coupon</label>
                 {{ form_widget(form.end, {'attr': { 'placeholder':'Expiration du coupon'}}) }}
            </div>
        </div>
        <div class="form-row mb-4">
            <div class="form-group col-md-4">
                <label for="inputCity">Code du coupon</label>
                {{ form_widget(form.code, {'attr': {'class': 'form-control', 'placeholder':'Code Secret'}}) }} 
            </div>
            <div class="form-group col-md-4">
                <label for="inputState">Nombre maximal d'utilisation</label>
                 {{ form_widget(form.max_usage, {'attr': {'class': 'form-control', 'placeholder':'Maximum'}}) }}
            </div>
            <div class="form-group col-md-4">
                <label for="inputState">Utilisation en cours</label>
                 {{ form_widget(form.current_usage, {'attr': {'class': 'form-control', 'placeholder':'Encours'}}) }}
            </div>
        </div>
        {{ form_widget(form._token) }}
        <button type="submit" class="btn btn-primary mt-3">{{ button_label|default('Ajout | Modification') }}</button>
    </form>
{{ form_end(form) }}

templates/coupon/edit.html.twig
{% extends 'admin/layout.html.twig' %}
{% block title %} {{parent()}} | Editer Coupon {% endblock %}

{% block dataStructured %}{% endblock %}

{% block stylesheets %}
    {{parent()}}
    <link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/datatables.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/custom_dt_html5.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/dt-global_style.css')}}">
    <style type="text/css">
        .widget-content-area{box-shadow: none;}
    </style>
{% endblock %}
{% block body_bo %}
<div class="layout-px-spacing">
    <div class="row layout-top-spacing">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12" style="margin-bottom:24px;">
            <div class="statbox widget box box-shadow">
                <div class="widget-header">                                
                    <div class="row">
                        <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                            <h4>Nouveau Coupon</h4>
    {{ include('coupon/_form.html.twig', {'button_label': 'Update'}) }}
                        </div>
                    </div>
                </div>
                <div class="widget-content widget-content-area">

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascripts %}
    {{parent()}}

{% endblock %}

templates/coupon/index.html.twig
{% extends 'admin/layout.html.twig' %}
{% block title %} {{parent()}} | Coupon {% endblock %}{% block stylesheets %}
{{parent()}}
<link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/datatables.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/custom_dt_html5.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/dt-global_style.css')}}">
<style type="text/css">
   .widget-content-area{box-shadow: none;}
</style>
{% endblock %}
{% block body_bo %}
<div class="layout-px-spacing">
   <div class="row layout-top-spacing">
      <div class="col-12 layout-spacing">
         <div class="widget widget-chart-three">
            <div class="widget-heading">
               <div class="">
                  <h5 class="">List de Coupon</h5>
               </div>
               <div class="dropdown  custom-dropdown">
                  <div class="dropdown  custom-dropdown">
                     <a class="btn" href="{{ path('coupon_new') }}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus">
                           <line x1="12" y1="5" x2="12" y2="19"></line>
                           <line x1="5" y1="12" x2="19" y2="12"></line>
                        </svg>
                        Ajouter
                     </a>
                  </div>
               </div>
            </div>
            <div class="widget-content widget-content-area br-6">
               <div class="table-responsive mb-4 mt-4">
                  <table id="html5-extension" class="table table-hover non-hover" style="width:100%">
                     <thead>
                        <tr>
                           <th>Nom</th>
                           <th>Type</th>
                           <th>Cout</th>
                           <th>Debut</th>
                           <th>Expiration</th>
                           <th>Max utilisation</th>
                           <th>Utilisations</th>
                           <th>Code</th>
                           <th>actions</th>
                        </tr>
                     </thead>
                     <tbody>
                        {% for coupon in coupons %}
                        <tr>
                           <td>{{ coupon.nom }}</td>
                           <td>

                                {% if(coupon.typeReduction) %}
                                    <span class="badge badge-success">Pourcentage</span>
                                {% else %}
                                    <span class="badge badge-danger">Prix</span>
                                {% endif %}
                           </td>
                           <td>{{ coupon.priceReduction }}</td>
                           <td>{{ coupon.start ? coupon.start|date('Y-m-d') : '' }}</td>
                           <td>{{ coupon.end ? coupon.end|date('Y-m-d') : '' }}</td>
                           <td>{{ coupon.maxUsage }}</td>
                           <td>{{ coupon.currentUsage }}</td>
                           <td><div class="badge badge-primary">{{ coupon.code }}</div></td>
                           <td>
                              <a href="{{ path('coupon_edit', {'id': coupon.id}) }}">edit</a>
                              {{ include('coupon/_delete_form.html.twig') }}
                           </td>
                        </tr>
                        {% else %}
                        <tr>
                           <td colspan="10">Aucun element trouve</td>
                        </tr>
                        {% endfor %}
                     </tbody>
                  </table>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
{% endblock %}
{% block javascripts %}
{{parent()}}
<script src="{{asset('assetsBo/plugins/table/datatable/datatables.js')}}"></script>
<!-- NOTE TO Use Copy CSV Excel PDF Print Options You Must Include These Files  -->
<script src="{{asset('assetsBo/plugins/table/datatable/button-ext/dataTables.buttons.min.js')}}"></script>
<script src="{{asset('assetsBo/plugins/table/datatable/button-ext/jszip.min.js')}}"></script>    
<script src="{{asset('assetsBo/plugins/table/datatable/button-ext/buttons.html5.min.js')}}"></script>
<script src="{{asset('assetsBo/plugins/table/datatable/button-ext/buttons.print.min.js')}}"></script>
<script>
   $('#sidebar .menu.menu-commande').addClass('active');
   $('#html5-extension').DataTable( {
       dom: '<"row"<"col-md-12"<"row"<"col-md-6"B><"col-md-6"f> > ><"col-md-12"rt> <"col-md-12"<"row"<"col-md-5"i><"col-md-7"p>>> >',
       buttons: {
           buttons: [
               { extend: 'copy', className: 'btn' },
               { extend: 'csv', className: 'btn' },
               { extend: 'excel', className: 'btn' },
               { extend: 'print', className: 'btn' }
           ]
       },
       "oLanguage": {
           "oPaginate": { "sPrevious": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-left"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>', "sNext": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>' },
           "sInfo": "voir page _PAGE_ of _PAGES_",
           "sSearch": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>',
           "sSearchPlaceholder": "Rechercher...",
          "sLengthMenu": "Results :  _MENU_",
       },
       "stripeClasses": [],
       "lengthMenu": [7, 10, 20, 50],
       "pageLength": 7 
   } );
      $('#sidebar .menu.menu-coupon').addClass('active');

</script>
{% endblock %}

templates/coupon/new.html.twig
{% extends 'admin/layout.html.twig' %}
{% block title %} {{parent()}} | Nouveau Coupon {% endblock %}

{% block dataStructured %}{% endblock %}

{% block stylesheets %}
    {{parent()}}
    <link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/datatables.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/custom_dt_html5.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/dt-global_style.css')}}">
    <style type="text/css">
        .widget-content-area{box-shadow: none;}
    </style>
{% endblock %}
{% block title_page %}Coupon{% endblock %}
{% block body_bo %}
    <div class="layout-px-spacing">
        <div class="row layout-top-spacing">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12" style="margin-bottom:24px;">
                <div class="statbox widget box box-shadow">
                    <div class="widget-header">                                
                        <div class="row">
                            <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                                <h4>Nouveau Coupon</h4>
                            </div>
                        </div>
                    </div>
                    <div class="widget-content widget-content-area">
                        {{ include('coupon/_form.html.twig') }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{parent()}}

{% endblock %}

templates/coupon/show.html.twig
{% extends 'admin/layout.html.twig' %}
{% block title %} {{parent()}} | Coupon {% endblock %}

{% block dataStructured %}{% endblock %}
{% block body %}
    <h1>Coupon</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ coupon.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ coupon.nom }}</td>
            </tr>
            <tr>
                <th>Type_reduction</th>
                <td>{{ coupon.typeReduction }}</td>
            </tr>
            <tr>
                <th>Price_reduction</th>
                <td>{{ coupon.priceReduction }}</td>
            </tr>
            <tr>
                <th>Start</th>
                <td>{{ coupon.start ? coupon.start|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>End</th>
                <td>{{ coupon.end ? coupon.end|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Max_usage</th>
                <td>{{ coupon.maxUsage }}</td>
            </tr>
            <tr>
                <th>Current_usage</th>
                <td>{{ coupon.currentUsage }}</td>
            </tr>
            <tr>
                <th>Code</th>
                <td>{{ coupon.code }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('coupon_index') }}">back to list</a>

    <a href="{{ path('coupon_edit', {'id': coupon.id}) }}">edit</a>

    {{ include('coupon/_delete_form.html.twig') }}
{% endblock %}