src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $price;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $old_price;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $quantity;

    /**
     * @ORM\Column(type="string", length=5000)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $type;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Panier", mappedBy="product")
     */
    private $formules;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commande", mappedBy="product",cascade={"persist"})
     */
    private $commandes;

    public function __construct()
    {
        $this->formules = new ArrayCollection();
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(?float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getOldPrice(): ?float
    {
        return $this->old_price;
    }

    public function setOldPrice(?float $old_price): self
    {
        $this->old_price = $old_price;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(?int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }


    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function setType(?int $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return Collection|Panier[]
     */
    public function getFormules(): Collection
    {
        return $this->formules;
    }

    public function addFormule(Panier $formule): self
    {
        if (!$this->formules->contains($formule)) {
            $this->formules[] = $formule;
            $formule->addProduct($this);
        }

        return $this;
    }

    public function removeFormule(Panier $formule): self
    {
        if ($this->formules->contains($formule)) {
            $this->formules->removeElement($formule);
            $formule->removeProduct($this);
        }

        return $this;
    }

    /**
     * @return Collection|Commande[]
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setProduct($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->contains($commande)) {
            $this->commandes->removeElement($commande);
            // set the owning side to null (unless already changed)
            if ($commande->getProduct() === $this) {
                $commande->setProduct(null);
            }
        }

        return $this;
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('price')
            ->add('old_price')
            ->add('quantity')
            ->add('description',TextareaType::class, array('attr' => array('class' => 'ckeditor')))
            ->add('image', FileType::class, [
                'required'=> false,
                'attr' => [
                    'accept' => 'image/*'
                ],
                'data_class' => null
            ])
            ->add('type',ChoiceType::class, array(
                    'choices'  => array(
                        'Simple' => 0,
                        'Reccurent' => 1,
                    ))
            );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Form\ProductType;
use App\Repository\ProductRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/dashboard/product")
 */
class ProductController extends AbstractController
{
    /**
     * @Route("/", name="product_index", methods={"GET"})
     */
    public function index(ProductRepository $productRepository): Response
    {
        return $this->render('product/index.html.twig', [
            'products' => $productRepository->findAll(),
        ]);
    }
    private function saveImage($uploadedFile,$dir){
        $destination = $this->getParameter('kernel.project_dir').$dir;
        $originalFilename = pathinfo($uploadedFile->getClientOriginalName(), PATHINFO_FILENAME);
        $name_file = $uploadedFile->getClientOriginalName();
        $sanitize_file = preg_replace('|[^-\\\\a-z0-9~+_.?\[\]^#=!&;,/:%@$\|*`\'<>"()\x80-\xff{}]|i', '', $name_file);
        $newFilename = uniqid().'_'.$sanitize_file;
        $uploadedFile->move(
            $destination,
            $destination.$newFilename
        );
        return $newFilename;
    }
    /**
     * @Route("/new", name="product_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $product = new Product();
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $uploadedFile = $form['image']->getData();
            $newFilename = "avatar.png";
            if($uploadedFile)
                $newFilename = $this->saveImage($uploadedFile,'/public/assets/img/products/');

            $product->setImage($newFilename);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($product);
            $entityManager->flush();
            return $this->redirectToRoute('product_index');
        }

        return $this->render('product/new.html.twig', [
            'product' => $product,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="product_show", methods={"GET"})
     */
    public function show(Product $product): Response
    {
        return $this->render('product/show.html.twig', [
            'product' => $product,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="product_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Product $product): Response
    {
        $form = $this->createForm(ProductType::class, $product);
        $old = $product->getImage();
        // $new = $form['image']->getData();
        $image_send = false;
        if(isset($_FILES["product"]) && $_FILES["product"]["size"]["image"]){
            $image_send = true;
        }

        if (isset($_POST['product'])) {

            $entityManager = $this->getDoctrine()->getManager();

            if($image_send){
                $form->handleRequest($request);
                $uploadedFile = $form['image']->getData();
                $newFilename = $this->saveImage($uploadedFile,'/public/assets/img/products/');
                $product->setImage($newFilename);
            }
            $product->setPrice(floatval(str_replace(',', ".", $_POST['product']['price'])));
            $product->setName($_POST['product']['name']);
            $product->setDescription($_POST['product']['description']);
            $product->setType($_POST['product']['type']);
            $product->setQuantity($_POST['product']['quantity']);
            $product->setOldPrice(floatval(str_replace(',', '.', $_POST['product']['old_price'])));

            $entityManager->persist($product);
            $entityManager->flush();
            return $this->redirectToRoute('product_index');
        }
        return $this->render('product/edit.html.twig', [
            'product' => $product,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/delete", name="product_delete", methods={"DELETE","GET"})
     */
    public function delete(Request $request, Product $product): Response
    {
        // if ($this->isCsrfTokenValid('delete'.$product->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($product);
            $entityManager->flush();
        // }

        return $this->redirectToRoute('product_index');
    }
}

templates/product/_delete_form.html.twig
<form method="post" action="{{ path('product_delete', {'id': product.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/product/_form.html.twig
<style type="text/css">
    button[type=submit]{float: right;}
</style>

{{ form_start(form) }}
    <div class="my-custom-class-for-errors">
        {{ form_errors(form) }}
    </div>

    <form>
        <div class="form-row mb-4">
            <div class="form-group col-md-8">
                <label for="inputEmail4">Nom du produit</label>
                 {{ form_widget(form.name, {'attr': {'class': 'form-control', 'placeholder':'Nom du produit'}}) }} 
            </div>
            <div class="form-group col-md-4">
                <label for="inputCity">Image du Produit</label>
                {{ form_widget(form.image, {'attr': {'class': 'form-control','type': 'decimal','required': false, 'placeholder':'Image du produit'}}) }} 
            </div>  
        </div>
       
        <div class="form-row mb-4">
            <div class="form-group col-md-3">
                <label for="inputCity">Prix Normal</label>
                {{ form_widget(form.old_price, {'attr': {'class': 'form-control', 'placeholder':'Prix normal produit'}}) }} 
            </div>
            <div class="form-group col-md-3">
                <label for="inputState">Prix Vente</label>
                 {{ form_widget(form.price, {'attr': {'class': 'form-control', 'placeholder':'Prix de Vente'}}) }}
            </div>
            <div class="form-group col-md-3">
                <label for="inputZip">Quantite</label>
                 {{ form_widget(form.quantity, {'attr': {'class': 'form-control', 'placeholder':'Quantite'}}) }}
            </div>
            <div class="form-group col-md-3">
                <label for="inputZip">Type de Produit</label>
                 {{ form_widget(form.type, {'attr': {'class': 'form-control', 'placeholder':'type'}}) }}
            </div>
        </div>
        <div class="form-group mb-4">
            <label for="inputAddress">Description</label>
             {{ form_widget(form.description, {'attr': {'class': 'form-control ckeditor', 'placeholder':'Quantite'}}) }}
        </div>    
        {{ form_widget(form._token) }}
        <button type="submit" class="btn btn-primary mt-3">{{ button_label|default('Ajouter le Produit') }}</button>
    </form>
{{ form_end(form) }}

templates/product/edit.html.twig
{% extends 'admin/layout.html.twig' %}
{% block title %} {{parent()}} | Produits {% endblock %}

{% block dataStructured %}{% endblock %}

{% block stylesheets %}
    {{parent()}}
{% endblock %}
{% block title_page %}Produits{% endblock %}
{% block body_bo %}
<div class="layout-px-spacing">
    <div class="row layout-top-spacing">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12" style="margin-bottom:24px;">
            <div class="statbox widget box box-shadow">
                <div class="widget-header">                                
                    <div class="row">
                        <div class="col-xl-12 col-md-12 col-sm-12 col-12 title-action-row">
                            <h4>Nouveau Produit</h4>
                            {{ include('product/_delete_form.html.twig') }}
                        </div>
                    </div>
                </div>
                <div class="widget-content widget-content-area">

                    {{ include('product/_form.html.twig', {'button_label': 'Mette a jour'}) }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascripts %}
    {{parent()}}
    <script type="text/javascript">
        $('#sidebar .menu.menu-produit').addClass('active');
    </script>
{% endblock %}

templates/product/index.html.twig
{% extends 'admin/layout.html.twig' %}
{% block title %} {{parent()}} | Produits {% endblock %}

{% block dataStructured %}{% endblock %}

{% block stylesheets %}
    {{parent()}}
    <link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/datatables.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/custom_dt_html5.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/dt-global_style.css')}}">
    <style type="text/css">
        .widget-content-area{box-shadow: none;}
    </style>
{% endblock %}
{% block title_page %}Produits{% endblock %}
{% block body_bo %}
    <div class="layout-px-spacing">
        <div class="row layout-top-spacing">
            <div class="col-12 layout-spacing">
                <div class="widget widget-chart-three">
                    <div class="widget-heading">
                        <div class="">
                            <h5 class="">List de Produits</h5>
                        </div>

                          <div class="dropdown  custom-dropdown">
                             <a class="btn" href="{{ path('product_new') }}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus">
                                   <line x1="12" y1="5" x2="12" y2="19"></line>
                                   <line x1="5" y1="12" x2="19" y2="12"></line>
                                </svg>
                                Ajouter
                             </a>
                          </div>

                    </div>

                    <div class="widget-content widget-content-area br-6">
                        <div class="table-responsive mb-4 mt-4">
                            <table id="html5-extension" class="table table-hover non-hover" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>Nom</th>
                                        <th>Prix</th>
                                        <th>Ancien Prix</th>
                                        <th>Quantite</th>
                                        <th>Image</th>
                                        <th>Type</th>
                                        <th>actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for product in products %}
                                    <tr>
                                        <td><a class="dropdown-item" href="{{ path('product_edit',{id:product.id}) }}">{{ product.name }}</a></td>
                                        <td>{{ product.price }}</td>
                                        <td>{{ product.oldPrice }}</td>
                                        <td>{{ product.quantity }}</td>
                                        <td>
                                            <div class="d-flex">
                                                <div class="usr-img-frame mr-2 rounded-circle">
                                                    <img alt="avatar" class="img-fluid rounded-circle" src="{{asset('assets/img/products/' ~ product.image)}}">
                                                </div>
                                            </div>
                                        </td>
                                        <td> 
                                            {% if(product.type) %}
                                            <span class="badge badge-info">Reccurent</span>
                                            {% else %}
                                            <span class="badge badge-success">Simple</span>
                                            {% endif %}
                                        </td>
                                        
                                        <td>
                                            {{ include('product/_delete_form.html.twig') }}
                                        </td>
                                    </tr>
                                {% else %}
                                    <tr>
                                        <td colspan="9">Auncun produit trouve</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{parent()}}

    <script src="{{asset('assetsBo/plugins/table/datatable/datatables.js')}}"></script>
    <!-- NOTE TO Use Copy CSV Excel PDF Print Options You Must Include These Files  -->
    <script src="{{asset('assetsBo/plugins/table/datatable/button-ext/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('assetsBo/plugins/table/datatable/button-ext/jszip.min.js')}}"></script>    
    <script src="{{asset('assetsBo/plugins/table/datatable/button-ext/buttons.html5.min.js')}}"></script>
    <script src="{{asset('assetsBo/plugins/table/datatable/button-ext/buttons.print.min.js')}}"></script>
    <script>
        $('#sidebar .menu.menu-produit').addClass('active');
        $('#html5-extension').DataTable( {
            dom: '<"row"<"col-md-12"<"row"<"col-md-6"B><"col-md-6"f> > ><"col-md-12"rt> <"col-md-12"<"row"<"col-md-5"i><"col-md-7"p>>> >',
            buttons: {
                buttons: [
                    { extend: 'copy', className: 'btn' },
                    { extend: 'csv', className: 'btn' },
                    { extend: 'excel', className: 'btn' },
                    { extend: 'print', className: 'btn' }
                ]
            },
            "oLanguage": {
                "oPaginate": { "sPrevious": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-left"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>', "sNext": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>' },
                "sInfo": "voir page _PAGE_ of _PAGES_",
                "sSearch": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>',
                "sSearchPlaceholder": "Rechercher...",
               "sLengthMenu": "Results :  _MENU_",
            },
            "stripeClasses": [],
            "lengthMenu": [7, 10, 20, 50],
            "pageLength": 7 
        } );
           $('#sidebar .menu.menu-product').addClass('active');

    </script>
{% endblock %}

templates/product/new.html.twig
{% extends 'admin/layout.html.twig' %}
{% block title %} {{parent()}} | Produits {% endblock %}

{% block dataStructured %}{% endblock %}

{% block stylesheets %}
    {{parent()}}
{% endblock %}
{% block title_page %}Produits{% endblock %}
{% block body_bo %}
    <div class="layout-px-spacing">
        <div class="row layout-top-spacing">
            
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12" style="margin-bottom:24px;">
                        <div class="statbox widget box box-shadow">
                            <div class="widget-header">                                
                                <div class="row">
                                    <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                                        <h4>Nouveau Produit</h4>
                                    </div>
                                </div>
                            </div>
                            <div class="widget-content widget-content-area">{{ include('product/_form.html.twig') }}
                            </div>
                        </div>
                    </div>


        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{parent()}}
    <script type="text/javascript">
        $('#sidebar .menu.menu-produit').addClass('active');
    </script>
{% endblock %}

templates/product/show.html.twig
{% extends 'admin/layout.html.twig' %}

{% block title %}Product{% endblock %}

{% block body %}
    <h1>Product</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ product.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ product.name }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ product.price }}</td>
            </tr>
            <tr>
                <th>Old_price</th>
                <td>{{ product.oldPrice }}</td>
            </tr>
            <tr>
                <th>Quantity</th>
                <td>{{ product.quantity }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ product.description }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ product.image }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ product.type }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('product_index') }}">back to list</a>

    <a href="{{ path('product_edit', {'id': product.id}) }}">edit</a>

    {{ include('product/_delete_form.html.twig') }}
{% endblock %}