src/Entity/Formule.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FormuleRepository")
 */
class Formule
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $message;


    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $month;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Abonnement", cascade={"persist", "remove"}, mappedBy="formule")
     */
    private $abonnements;

    /**
     * @ORM\Column(type="float")
     */
    private $price_shipping;

    /**
     * @ORM\Column(type="integer")
     */
    private $try_days;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $stripe_product_id;

    public function __construct()
    {
        $this->abonnements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(?string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getAbonnement(): ?Abonnement
    {
        return $this->abonnement;
    }

    public function setAbonnement(?Abonnement $abonnement): self
    {
        $this->abonnement = $abonnement;

        return $this;
    }


    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getMonth(): ?int
    {
        return $this->month;
    }

    public function setMonth(int $month): self
    {
        $this->month = $month;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Abonnement[]
     */
    public function getAbonnements(): Collection
    {
        return $this->abonnements;
    }

    public function addAbonnement(Abonnement $abonnement): self
    {
        if (!$this->abonnements->contains($abonnement)) {
            $this->abonnements[] = $abonnement;
            $abonnement->setFormule($this);
        }

        return $this;
    }

    public function removeAbonnement(Abonnement $abonnement): self
    {
        if ($this->abonnements->contains($abonnement)) {
            $this->abonnements->removeElement($abonnement);
            // set the owning side to null (unless already changed)
            if ($abonnement->getFormule() === $this) {
                $abonnement->setFormule(null);
            }
        }

        return $this;
    }

    public function getPriceShipping(): ?float
    {
        return $this->price_shipping;
    }

    public function setPriceShipping(float $price_shipping): self
    {
        $this->price_shipping = $price_shipping;

        return $this;
    }

    public function getTryDays(): ?int
    {
        return $this->try_days;
    }

    public function setTryDays(int $try_days): self
    {
        $this->try_days = $try_days;

        return $this;
    }

    public function __toString (  ) : string{
        return $this->getName();
    }

    public function getStripeProductId(): ?string
    {
        return $this->stripe_product_id;
    }

    public function setStripeProductId(?string $stripe_product_id): self
    {
        $this->stripe_product_id = $stripe_product_id;

        return $this;
    }
}

src/Form/FormuleType.php
<?php

namespace App\Form;

use App\Entity\Formule;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class FormuleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('message')
            ->add('price')
            ->add('month', ChoiceType::class, [
                'choices'  => [
                    '1' => 1,
                    '12' => 12,
                ],
            ])
            ->add('name')
            ->add('price_shipping')
            ->add('try_days')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Formule::class,
        ]);
    }
}

src/Controller/FormuleController.php
<?php

namespace App\Controller;

use App\Entity\Formule;
use App\Form\FormuleType;
use App\Repository\FormuleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\StripeService;

/**
 * @Route("/dashboard/formule")
 */
class FormuleController extends AbstractController
{
    private $stripe_s;

    public function __construct(StripeService $stripe_s){
        $this->stripe_s = $stripe_s;
    }

    /**
     * @Route("/", name="formule_index", methods={"GET"})
     */
    public function index(FormuleRepository $formuleRepository): Response
    {
        return $this->render('formule/index.html.twig', [
            'formules' => $formuleRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="formule_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $formule = new Formule();
        $stripeProducts =  $this->stripe_s->getAllProduct();
        if(!count($stripeProducts)){
            $stripeProducts = [$this->stripe_s->createProduct()];
        }

        $form = $this->createForm(FormuleType::class, $formule);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $formule->setStripeProductId($request->request->get('stripe_product_id'));
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($formule);
            $entityManager->flush();

            return $this->redirectToRoute('formule_index');
        }

        return $this->render('formule/new.html.twig', [
            'formule' => $formule,
            'form' => $form->createView(),
            'stripeProducts'=>$stripeProducts
        ]);
    }

    /**
     * @Route("/{id}", name="formule_show", methods={"GET"})
     */
    public function show(Formule $formule): Response
    {
        return $this->render('formule/show.html.twig', [
            'formule' => $formule,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="formule_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Formule $formule): Response
    {
        $stripeProducts =  $this->stripe_s->getAllProduct();
        if(!count($stripeProducts)){
            $stripeProducts = [$this->stripe_s->createProduct()];
        }

        $form = $this->createForm(FormuleType::class, $formule);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $formule->setStripeProductId($request->request->get('stripe_product_id'));
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('formule_index');
        }

        return $this->render('formule/edit.html.twig', [
            'formule' => $formule,
            'form' => $form->createView(),
            'stripeProducts'=>$stripeProducts
        ]);
    }

    /**
     * @Route("/{id}", name="formule_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Formule $formule): Response
    {
        if ($this->isCsrfTokenValid('delete'.$formule->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($formule);
            $entityManager->flush();
        }

        return $this->redirectToRoute('formule_index');
    }
}

templates/formule/_delete_form.html.twig
<form method="post" action="{{ path('formule_delete', {'id': formule.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ formule.id) }}">
    <button class="btn">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2">
            <polyline points="3 6 5 6 21 6"></polyline>
            <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>
            <line x1="10" y1="11" x2="10" y2="17"></line>
            <line x1="14" y1="11" x2="14" y2="17"></line>
        </svg>
    </button>
</form>

templates/formule/_form.html.twig
<style type="text/css">
    button[type=submit]{float: right;}
</style>

{{ form_start(form) }}
    <div class="my-custom-class-for-errors">
        {{ form_errors(form) }}
    </div>

    <form>
        <div class="form-row mb-4">
            <div class="form-group col-md-4">
                <label for="inputEmail4">Nom de la formule</label>
                 {{ form_widget(form.name, {'attr': {'class': 'form-control', 'placeholder':'Nom'}}) }} 
            </div>
            <div class="form-group col-md-4">
                <label for="inputCity">Cout de l'anonnement</label>
                {{ form_widget(form.price, {'attr': {'class': 'form-control','type': 'decimal','required': false, 'placeholder':'Cout de la formule'}}) }} 
            </div>  
            <div class="form-group col-md-4">
                <label for="inputCity">stripe product id</label>
                <select name="stripe_product_id" class="form-control" required="true">
                    {% for product in stripeProducts %}
                        <option value="{{product.id}}" {% if formule.getStripeProductId == product.id %} selected="selected" {% endif %}>
                            {{product.name}}
                        </option>
                    {% endfor %}
                </select>
            </div>  
        </div>
       
        <div class="form-row mb-4">
            <div class="form-group col-md-4">
                <label for="inputCity">Nombre de mois</label>
                {{ form_widget(form.month, {'attr': {'class': 'form-control', 'placeholder':'Nombre de mois'}}) }} 
            </div>
            <div class="form-group col-md-4">
                <label for="inputState">Prix de Livraison</label>
                 {{ form_widget(form.price_shipping, {'attr': {'class': 'form-control', 'placeholder':'Prix de Livraison'}}) }}
            </div>
            <div class="form-group col-md-4">
                <label for="inputZip">Jour d'essaie</label>
                 {{ form_widget(form.try_days, {'attr': {'class': 'form-control', 'placeholder':'Jour pour essayer'}}) }}
            </div>
        </div>
        <div class="form-group mb-4">
            <label for="inputAddress">Description</label>
             {{ form_widget(form.message, {'attr': {'class': 'form-control ckeditor', 'placeholder':'Description'}}) }}
        </div>    
        {{ form_widget(form._token) }}
        <button type="submit" class="btn btn-primary mt-3">{{ button_label|default('Ajout | Modification') }}</button>
    </form>
{{ form_end(form) }}

templates/formule/edit.html.twig
{% extends 'admin/layout.html.twig' %}
{% block title %} {{parent()}} | Editer Formule {% endblock %}

{% block dataStructured %}{% endblock %}

{% block stylesheets %}
    {{parent()}}
    <link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/datatables.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/custom_dt_html5.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/dt-global_style.css')}}">
    <style type="text/css">
        .widget-content-area{box-shadow: none;}
    </style>
{% endblock %}
{% block body_bo %}
<div class="layout-px-spacing">
    <div class="row layout-top-spacing">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12" style="margin-bottom:24px;">
            <div class="statbox widget box box-shadow">
                <div class="widget-header">                                
                    <div class="row">
                        <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                            <h4>Edition Formule</h4>
    {{ include('formule/_form.html.twig', {'button_label': 'Update'}) }}
                        </div>
                    </div>
                </div>
                <div class="widget-content widget-content-area">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascripts %}
    {{parent()}}

{% endblock %}

templates/formule/index.html.twig
{% extends 'admin/layout.html.twig' %}
{% block title %} {{parent()}} | Formule {% endblock %}{% block stylesheets %}
{{parent()}}
<link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/datatables.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/custom_dt_html5.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/dt-global_style.css')}}">
<style type="text/css">
   .widget-content-area{box-shadow: none;}
</style>
{% endblock %}
{% block body_bo %}
<div class="layout-px-spacing">
   <div class="row layout-top-spacing">
      <div class="col-12 layout-spacing">
         <div class="widget widget-chart-three">
            <div class="widget-heading">
               <div class="">
                  <h5 class="">List de Formule</h5>
               </div>
               <div class="dropdown  custom-dropdown">
                  <div class="dropdown  custom-dropdown">
                     <a class="btn" href="{{ path('formule_new') }}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus">
                           <line x1="12" y1="5" x2="12" y2="19"></line>
                           <line x1="5" y1="12" x2="19" y2="12"></line>
                        </svg>
                        Ajouter
                     </a>
                  </div>
               </div>
            </div>
            <div class="widget-content widget-content-area br-6">
               <div class="table-responsive mb-4 mt-4">
                  <table id="html5-extension" class="table table-hover non-hover" style="width:100%">
                     <thead>
                        <tr>
                           <th>Nom</th>
                           <th>Prix</th>
                           <th>Nombre de mois</th>
                           <th>Prix de Livraison</th>
                           <th>Jours d'essaie</th>
                           <th>actions</th>
                        </tr>
                     </thead>
                     <tbody>
                        {% for formule in formules %}
                        <tr>
                           <td>{{ formule.name }}</td>
                           <td>{{ formule.price }}</td>
                           <td>{{ formule.month }}</td>
                           <td>{{ formule.priceShipping }}</td>
                           <td>{{ formule.tryDays }}</td>
                           <td>
                              <a href="{{ path('formule_edit', {'id': formule.id}) }}">Editer</a>
                              {{ include('formule/_delete_form.html.twig') }}
                           </td>
                        </tr>
                        {% else %}
                        <tr>
                           <td colspan="8">Aucun element trouve</td>
                        </tr>
                        {% endfor %}
                     </tbody>
                  </table>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
{% endblock %}
{% block javascripts %}
{{parent()}}
<script src="{{asset('assetsBo/plugins/table/datatable/datatables.js')}}"></script>
<!-- NOTE TO Use Copy CSV Excel PDF Print Options You Must Include These Files  -->
<script src="{{asset('assetsBo/plugins/table/datatable/button-ext/dataTables.buttons.min.js')}}"></script>
<script src="{{asset('assetsBo/plugins/table/datatable/button-ext/jszip.min.js')}}"></script>    
<script src="{{asset('assetsBo/plugins/table/datatable/button-ext/buttons.html5.min.js')}}"></script>
<script src="{{asset('assetsBo/plugins/table/datatable/button-ext/buttons.print.min.js')}}"></script>
<script>
   $('#sidebar .menu.menu-commande').addClass('active');
   $('#html5-extension').DataTable( {
       dom: '<"row"<"col-md-12"<"row"<"col-md-6"B><"col-md-6"f> > ><"col-md-12"rt> <"col-md-12"<"row"<"col-md-5"i><"col-md-7"p>>> >',
       buttons: {
           buttons: [
               { extend: 'copy', className: 'btn' },
               { extend: 'csv', className: 'btn' },
               { extend: 'excel', className: 'btn' },
               { extend: 'print', className: 'btn' }
           ]
       },
       "oLanguage": {
           "oPaginate": { "sPrevious": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-left"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>', "sNext": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>' },
           "sInfo": "voir page _PAGE_ of _PAGES_",
           "sSearch": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>',
           "sSearchPlaceholder": "Rechercher...",
          "sLengthMenu": "Results :  _MENU_",
       },
       "stripeClasses": [],
       "lengthMenu": [7, 10, 20, 50],
       "pageLength": 7 
   } );
      $('#sidebar .menu.menu-formule').addClass('active');

</script>
{% endblock %}

templates/formule/new.html.twig
{% extends 'admin/layout.html.twig' %}
{% block title %} {{parent()}} | Nouveau Formule {% endblock %}

{% block dataStructured %}{% endblock %}

{% block stylesheets %}
    {{parent()}}
    <link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/datatables.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/custom_dt_html5.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('assetsBo/plugins/table/datatable/dt-global_style.css')}}">
    <style type="text/css">
        .widget-content-area{box-shadow: none;}
    </style>
{% endblock %}
{% block title_page %}Formule{% endblock %}
{% block body_bo %}
    <div class="layout-px-spacing">
        <div class="row layout-top-spacing">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12" style="margin-bottom:24px;">
                <div class="statbox widget box box-shadow">
                    <div class="widget-header">                                
                        <div class="row">
                            <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                                <h4>Nouveau Formule</h4>
                            </div>
                        </div>
                    </div>
                    <div class="widget-content widget-content-area" style="height: 571px;">
                        {{ include('formule/_form.html.twig') }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{parent()}}

{% endblock %}

templates/formule/show.html.twig
{% extends 'admin/layout.html.twig' %}
{% block title %} {{parent()}} | Formule {% endblock %}

{% block dataStructured %}{% endblock %}
{% block body %}
    <h1>Formule</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ formule.id }}</td>
            </tr>
            <tr>
                <th>Message</th>
                <td>{{ formule.message }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ formule.price }}</td>
            </tr>
            <tr>
                <th>Month</th>
                <td>{{ formule.month }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ formule.name }}</td>
            </tr>
            <tr>
                <th>Price_shipping</th>
                <td>{{ formule.priceShipping }}</td>
            </tr>
            <tr>
                <th>Try_days</th>
                <td>{{ formule.tryDays }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('formule_index') }}">back to list</a>

    <a href="{{ path('formule_edit', {'id': formule.id}) }}">edit</a>

    {{ include('formule/_delete_form.html.twig') }}
{% endblock %}